# -*- coding: utf-8 -*-
"""add.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDJreKJKbFq782AlQ5-5ct31WRQGE6lq
"""

def add (v1):
   return v1+4