# -*- coding: utf-8 -*-
"""DataMemory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOHVk07qa3p3PdwaBQY-YcDLPclPfC99
"""

def datamemory(adress, writedata,Memwrite,Memread):
  return datamemory,
  return readdata