# -*- coding: utf-8 -*-
"""extensor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hH2msxFGNm8zmoTHS0zz_qtNzvlstM3A
"""

def signExtensed (x):
  bin_x = bin(x)
  return '0000000000000000'+bin_x[2:]

signExtensed(3)

