# -*- coding: utf-8 -*-
"""Mux.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MjoRWfVEHAofoFLfDKXde_X8Zf-Ez3U
"""



def mux(a,b,x):
  if (x==0): 
    return a
  else :
    return b
